## Learning to count sequences of ones with RNNs: Keras implementation

Inspired from http://monik.in/a-noobs-guide-to-implementing-rnn-lstm-using-tensorflow/

Data preprocessing taken from https://github.com/pilipolio/python-ml-notebooks/blob/master/rnn/LSTM_toy.ipynb

In [31]:
import numpy as np
import tensorflow as tf
sess = tf.InteractiveSession()

tf.__version__

'0.12.1'

In [32]:
n_seqs = 500000
seq_length = 5

training_seqs = np.random.randint(2, size=(n_seqs, seq_length, 1)).astype(np.float64)
targets = training_seqs.sum(axis=1, dtype=np.float64)

print(training_seqs[:3, :, 0])
print(targets[:3])

n_test_seqs = 1000
test_seqs = []
test_targets = []
#while len(test_seqs) < n_test_seqs:
#    seq = np.random.randint(2, size=(1, seq_length, 1)).astype(np.float64)

[[ 1.  1.  0.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  1.  1.]]
[[ 3.]
 [ 3.]
 [ 3.]]


## LSTM model in Keras

In [50]:
from keras.layers.recurrent import LSTM
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop

num_hidden = 5

model = Sequential()
model.add(LSTM(num_hidden, input_shape=(seq_length, 1), activation='sigmoid', inner_activation='hard_sigmoid'))
model.add(Dense(1))
# model.add(Activation('softmax'))
optimizer = RMSprop(lr=0.01)
model.compile(optimizer=optimizer,
              loss='mse')

model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
lstm_17 (LSTM)                   (None, 5)             140         lstm_input_16[0][0]              
____________________________________________________________________________________________________
dense_14 (Dense)                 (None, 1)             6           lstm_17[0][0]                    
Total params: 146
Trainable params: 146
Non-trainable params: 0
____________________________________________________________________________________________________


## Predicting the sum at the end of the sequence

In [51]:
model.fit(training_seqs, targets, batch_size=1000, nb_epoch=10, verbose=2)

Epoch 1/10
9s - loss: 0.2929 - acc: 0.8436
Epoch 2/10
7s - loss: 0.0114 - acc: 1.0000
Epoch 3/10
8s - loss: 0.0105 - acc: 1.0000
Epoch 4/10
9s - loss: 0.0098 - acc: 1.0000
Epoch 5/10
8s - loss: 0.0091 - acc: 1.0000
Epoch 6/10
8s - loss: 0.0084 - acc: 1.0000
Epoch 7/10
8s - loss: 0.0078 - acc: 1.0000
Epoch 8/10
8s - loss: 0.0073 - acc: 1.0000
Epoch 9/10
8s - loss: 0.0068 - acc: 1.0000
Epoch 10/10
8s - loss: 0.0064 - acc: 1.0000


## Inspecting predictions for any sequence

In [44]:
x = np.array([1, 1, 1, 1, 1]).reshape((1, -1, 1))
np.round(model.predict(x, verbose=0)[0])

array([ 5.], dtype=float32)

In [ ]:
# score = model.evaluate(X_test, Y_test, batch_size=16)